### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by maropook**
## iOS and Android
- Unify function names and data types that can be obtained from observers for ios and android

- Added function sendDataMessage to send messages

- Added ChimeDataMessageObserver observer to detect receipt of messages

- Refactor of example

- Refactor

- Update README.md

- Update CHANGELOG.md.

## iOS 
- I modified eggnstone_amazon_chime/ios to build by simply replacing the following 4 files in eggnstone_amazon_chime/ios with reference to readme.

  - AmazonChimeSDK.framework
  - AmazonChimeSDK.xcframework
  - AmazonChimeSDKMedia.framework
  - AmazonChimeSDKMedia.xcframework
  - Fixed to be able to build with simulator

- Added function getVersion to get SDK version

### CODE REVIEW

**Comment by eggnstone** [comment]
Hi @maropook !
Thank you for your great work! Cool!
It will take me a bit of time to check the PR but I hope I can include it soon.

**Comment by maropook** [comment]
Hi @eggnstone 
Thank you for your kind comments.
We would like to refactor this pull request a bit more.
Therefore, may we ask that you wait a little longer for review? We will report back to you when it is completed.

**Comment by eggnstone** [comment]
> Hi @eggnstone Thank you for your kind comments. We would like to refactor this pull request a bit more. Therefore, may we ask that you wait a little longer for review? We will report back to you when it is completed.

Sure!

**Comment by maropook** [comment]
Hi @eggnstone 
Thank you very much for your patience.
The refactoring is finished.
I would be happy to review it when you are available.

**Comment by maropook** [comment]
@eggnstone 
Sorry.
I merged by mistake.
However, I could confirm that there was no problem at all, since no new updates were included.
Therefore, we have re-created a new pull request.(https://github.com/eggnstone/eggnstone_amazon_chime/pull/30)
I am really sorry.

**Pull request merged**
